name: Deploy to static-sites server

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy the statics
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 157.90.121.18
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 33322
        debug: true
        use_insecure_cipher: true
        script: |
          whoami
          ls -al
          systemctl status caddy