name: Deploy to static-sites server

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the statics
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.STATIC_HOST }}
        username: ${{ secrets.STATIC_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.STATIC_PORT }}
        command: |
          whoami
          ls -al
          systemctl status caddy