name: Deploy to static-sites server

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy the statics
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.STATIC_HOST }}
        username: ${{ secrets.STATIC_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.STATIC_PORT }}
        script: |
          docker rm -f crypter
          docker run -d --name crypter -p 8080:8080 ghcr.io/infiniteloopcloud/crypter:${GITHUB_REF/refs\/tags\//}
          rm -f /etc/caddy/crypter.caddy
          tee -a /etc/caddy/crypter.caddy << END
          crypter.infiniteloop.cloud {
            tls qwer.kockaa@gmail.com
            reverse_proxy localhost:8080
          }
          END
          systemctl restart caddy