name: Deploy to static-sites server

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the statics
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.STATIC_HOST }}
        username: ${{ secrets.STATIC_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.STATIC_PORT }}
        script: |
          whoami
          ls -al
          systemctl status caddy